# DEFINATIONS
SOLUTION_PACKAGE_NAME = "@solution"

# TYPESCRIPT_LIBRARY_DEFAULTS
TYPESCRIPT_PRODMODE_TARGET = "es2015"
TYPESCRIPT_DEVMODE_TARGET = "es2015"
TYPESCRIPT_PRODMODE_MODULE = "commonjs"
TYPESCRIPT_DEVMODE_MODULE = "commonjs"
